cat *.sh.o* |grep "Date" -v>spin.dat
#cat spin.dat |grep "s" >spins.dat
#cat spin.dat |grep "p1" >spinp1.dat
#cat spin.dat |grep "h1" >horb1.dat
#cat spin.dat |grep "p2" >spinp2.dat
#cat spin.dat |grep "h2" >horb2.dat
#cat spin.dat |grep "p3" >spinp3.dat
#cat spin.dat |grep "h3" >horb3.dat
#cat spin.dat |grep "p4" >spinp4.dat
#cat spin.dat |grep "h4" >horb4.dat
